kube-prometheus-stack:
  prometheus-node-exporter:
    ## If true, node-exporter pods mounts host / at /host/root
    ## Set to false because of https://github.com/prometheus-community/helm-charts/issues/467
    ##
    hostRootFsMount: false

  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: 'spring'
          kubernetes_sd_configs:
            - role: service

          relabel_configs:
          - action: replace
            source_labels: [ __meta_kubernetes_service_annotation_spring_io_metric_path ]
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__meta_kubernetes_service_annotation_spring_io_scrape]
            action: keep
            regex: true
